# -*- coding: utf-8 -*-
"""
Created on Fri Feb  7 22:30:28 2020

@author: HASSAN ENTERPRISES
"""

from tkinter import *
import tkinter as tkr
def mmm():
    a=v.get()
    print(a)
root=Tk()
root.title("making a gui of students regristration form")
root.geometry("1000x500")
Label(root,text="FIRST NAME").grid(row=0,column=0)
Entry(root).grid(row=0,column=1)
Label(root,text="LAST NAME").grid(row=1,column=0)
Entry(root).grid(row=1,column=1)
Label(root,text="DATE OF BIRTH").grid(row=2,column=1)
list=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31]
c=tkr.IntVar()
droplist=OptionMenu(root,c,*list)
c.set("Date")
droplist.grid(row=2,column=2)
list1=["JANUARY","FEBRUARY","MARCH","APRIL","MAY","JUN","JULY","AUGUEST","SEPTEMBER","OCTOBER","NOVEMBER","DECEMBER"]
i=tkr.StringVar()
droplist=OptionMenu(root,i,*list1)
i.set("Month")
droplist.grid(row=2,column=3)
list2=[1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020]
y=tkr.IntVar()
droplist=OptionMenu(root,y,*list2)
y.set("Year")
droplist.grid(row=2,column=4)
Label(root,text="EMAIL.ID").grid(row=3,column=0)
Entry(root).grid(row=3,column=1)
Label(root,text="GENDER").grid(row=4,column=0)
v=IntVar()
Radiobutton(root,text="Male",variable=v,value=1,command=mmm).grid(row=4,column=1)
Radiobutton(root,text="Female",variable=v,value=2,command=mmm).grid(row=4,column=2)
Label(root,text="CITY").grid(row=5,column=0)
Entry(root).grid(row=5,column=1)
Label(root,text="PIN CODE").grid(row=6,column=0)
Entry(root).grid(row=6,column=1)
Label(root,text="COUNTRY").grid(row=7,column=0)
Entry(root).grid(row=7,column=1)
Label(root,text="HOBBIES").grid(row=8,column=0)
Checkbutton(root,text="Drawing").grid(row=8,column=1)
Checkbutton(root,text="Singing").grid(row=8,column=2)
Checkbutton(root,text="Dancing").grid(row=8,column=3)
Checkbutton(root,text="Sketching").grid(row=8,column=4)
Label(root,text="QUALIFICATION").grid(row=9,column=0)
Label(root,text="S.NO EXAMINATION").grid(row=9,column=2)
Label(root,text="BOARD").grid(row=9,column=3)
Label(root,text="percentage").grid(row=9,column=4)
Label(root,text="YEAR OF PASSING").grid(row=9,column=5)
Label(root,text="CLASS 10").grid(row=10,column=2)
Label(root,text="CLASS 11").grid(row=11,column=2)
Label(root,text="CLASS 12").grid(row=12,column=2)
Label(root,text="BACHLORS").grid(row=13,column=2)
Label(root,text="MASTERS").grid(row=14,column=2)
Entry(root).grid(row=10,column=3)
Entry(root).grid(row=10,column=4)
Entry(root).grid(row=10,column=5)
Entry(root).grid(row=11,column=3)
Entry(root).grid(row=11,column=4)
Entry(root).grid(row=11,column=5)
Entry(root).grid(row=12,column=3)
Entry(root).grid(row=12,column=4)
Entry(root).grid(row=12,column=5)
Entry(root).grid(row=13,column=3)
Entry(root).grid(row=13,column=4)
Entry(root).grid(row=13,column=5)
Entry(root).grid(row=14,column=3)
Entry(root).grid(row=14,column=4)
Entry(root).grid(row=14,column=5)
Label(root,text="COURSES APPLIED FOR").grid(row=15,column=0)
Checkbutton(root,text="B.CA").grid(row=15,column=1)
Checkbutton(root,text="B.com").grid(row=15,column=2)
Checkbutton(root,text="B.Sc").grid(row=15,column=3)
Checkbutton(root,text="BBA").grid(row=15,column=4)
Button(root,text="submit",width=20,bg="red",fg="white").grid(row=16,column=2)
Button(root,text="reset",width=20,bg="red",fg="white").grid(row=16,column=3)
root.mainloop()